import { serve } from "bun";
import { join, resolve } from "path";
import { readFile } from "fs/promises";
import { DASHBOARD_PORT, BROKER_URL } from "../shared/constants";
import { ensureBroker } from "../broker/launcher";

const PUBLIC_DIR = join(import.meta.dir, "public");

// In production builds, embedded-html.ts is generated by CI with the HTML inlined.
// In dev mode, we read the file directly.
let DASHBOARD_HTML: string;
try {
  const { DASHBOARD_HTML: embedded } = await import("./embedded-html");
  DASHBOARD_HTML = embedded;
} catch {
  // Dev mode fallback: read from disk
  try {
    DASHBOARD_HTML = await Bun.file(join(PUBLIC_DIR, "index.html")).text();
  } catch {
    DASHBOARD_HTML = "<h1>Dashboard unavailable</h1>";
  }
}

async function brokerGet(path: string): Promise<unknown> {
  const res = await fetch(`${BROKER_URL}${path}`);
  if (!res.ok) throw new Error(`Broker error ${res.status}`);
  return res.json();
}

function createSSEStream(): ReadableStream {
  let interval: ReturnType<typeof setInterval>;
  return new ReadableStream({
    start(controller) {
      const enc = new TextEncoder();
      const send = async () => {
        try {
          const stats = await brokerGet("/stats");
          controller.enqueue(enc.encode(`data: ${JSON.stringify(stats)}\n\n`));
        } catch {}
      };
      send();
      interval = setInterval(send, 2000);
    },
    cancel() {
      clearInterval(interval);
    },
  });
}

async function handler(req: Request): Promise<Response> {
  const url = new URL(req.url);
  const path = url.pathname;
  // C5: no CORS — dashboard is local-only, no cross-origin access needed
  const headers = { "Cache-Control": "no-cache" };

  // Proxy al broker
  if (path === "/api/peers") {
    const data = await brokerGet("/peers").catch(() => []);
    return Response.json(data, { headers });
  }

  if (path === "/api/stats") {
    const data = await brokerGet("/stats").catch(() => ({ total: 0, working: 0, waiting: 0, idle: 0, peers: [] }));
    return Response.json(data, { headers });
  }

  if (path === "/api/connections") {
    const data = await brokerGet("/connections").catch(() => []);
    return Response.json(data, { headers });
  }

  if (path === "/api/activity") {
    const limit = Math.min(Number(url.searchParams.get("limit")) || 50, 500); // H3: cap DoS
    const data = await brokerGet(`/activity?limit=${limit}`).catch(() => []);
    return Response.json(data, { headers });
  }

  if (path === "/api/stream") {
    const stream = createSSEStream();
    return new Response(stream, {
      headers: { ...headers, "Content-Type": "text/event-stream", "Connection": "keep-alive" },
    });
  }

  // Servir archivos estáticos con sanitización de path traversal
  if (path === "/" || path === "/index.html") {
    return new Response(DASHBOARD_HTML, { headers: { ...headers, "Content-Type": "text/html" } });
  }

  if (path === "/logo.svg") {
    try {
      const { LOGO_SVG } = await import("./embedded-icons");
      return new Response(LOGO_SVG, { headers: { ...headers, "Content-Type": "image/svg+xml" } });
    } catch {}
    try {
      const content = await readFile(join(PUBLIC_DIR, "logo.svg"), "utf-8");
      return new Response(content, { headers: { ...headers, "Content-Type": "image/svg+xml" } });
    } catch {
      return new Response("", { status: 404 });
    }
  }

  if (path.startsWith("/icons/")) {
    const filename = path.slice("/icons/".length);
    // Try embedded icons first (compiled binary)
    try {
      const { EMBEDDED_ICONS } = await import("./embedded-icons");
      const icon = EMBEDDED_ICONS[filename];
      if (icon) {
        const buf = Buffer.from(icon.data, "base64");
        return new Response(buf, { headers: { ...headers, "Content-Type": icon.mime } });
      }
    } catch {}
    // Fallback: serve from disk (dev mode)
    try {
      const safePath = resolve(PUBLIC_DIR, "icons", filename);
      if (!safePath.startsWith(PUBLIC_DIR)) return new Response("Forbidden", { status: 403 });
      const content = await readFile(safePath);
      const ext = filename.split(".").pop() ?? "";
      const types: Record<string, string> = { ico: "image/x-icon", png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", svg: "image/svg+xml" };
      return new Response(content, { headers: { ...headers, "Content-Type": types[ext] ?? "application/octet-stream" } });
    } catch {
      return new Response("", { status: 404 });
    }
  }

  if (path.endsWith(".css") || path.endsWith(".js")) {
    try {
      const safePath = resolve(PUBLIC_DIR, path.slice(1));
      if (!safePath.startsWith(PUBLIC_DIR)) return new Response("Forbidden", { status: 403 });
      const content = await readFile(safePath);
      const ext = path.split(".").pop() ?? "";
      const types: Record<string, string> = { css: "text/css", js: "application/javascript" };
      return new Response(content, { headers: { ...headers, "Content-Type": types[ext] ?? "application/octet-stream" } });
    } catch {
      return new Response("", { status: 404 });
    }
  }

  return new Response("Not found", { status: 404 });
}

export async function startDashboard(port = DASHBOARD_PORT): Promise<void> {
  // Asegurar que el broker está corriendo
  await ensureBroker();

  let server;
  let actualPort = port;
  for (let attempt = 0; attempt < 10; attempt++) {
    try {
      server = serve({ port: actualPort, hostname: "127.0.0.1", fetch: handler }); // C1: loopback only
      break;
    } catch (e) {
      if (String(e).includes("already in use") || String(e).includes("in use")) {
        actualPort++;
      } else {
        throw e;
      }
    }
  }

  const bold = "\x1b[1m", dim = "\x1b[2m", r = "\x1b[0m";
  console.log(`\n  ${bold}agents-mesh${r}  ${dim}dashboard${r}\n\n  ${bold}🟢  http://localhost:${actualPort}${r}\n  ${dim}broker  →  localhost:${BROKER_URL.split(":")[2]}${r}\n  ${dim}Ctrl+C  →  cerrar${r}\n`);

  process.on("SIGINT",  () => { server?.stop(); process.exit(0); });
  process.on("SIGTERM", () => { server?.stop(); process.exit(0); });

  await new Promise(() => {});
}

if (import.meta.main) {
  await startDashboard();
}
