#!/usr/bin/env bun
// Generates src/dashboard/embedded-html.ts with the dashboard HTML inlined.
// Icons are inlined as base64 data URIs so the binary is fully self-contained.

import { join } from "path";
import { writeFileSync } from "fs";

const root = join(import.meta.dir, "..");
const htmlPath = join(root, "src", "dashboard", "public", "index.html");
const iconsDir = join(root, "src", "dashboard", "public", "icons");
const outPath = join(root, "src", "dashboard", "embedded-html.ts");

// Load icons as base64 data URIs
const MIME: Record<string, string> = {
  ico: "image/x-icon",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  svg: "image/svg+xml; charset=utf-8",
};

const iconFiles = ["claude-code.svg", "gemini-cli.svg", "opencode.svg", "copilot.svg", "codex.svg"];
const iconMap: Record<string, string> = {};

for (const file of iconFiles) {
  const ext = file.split(".").pop()!;
  const mime = MIME[ext] ?? "application/octet-stream";
  const bytes = await Bun.file(join(iconsDir, file)).arrayBuffer();
  const b64 = Buffer.from(bytes).toString("base64");
  iconMap[`/icons/${file}`] = `data:${mime};base64,${b64}`;
}

let html = await Bun.file(htmlPath).text();

// Replace icon src references with inline base64
for (const [path, dataUri] of Object.entries(iconMap)) {
  html = html.replaceAll(`'${path}'`, `'${dataUri}'`);
  html = html.replaceAll(`"${path}"`, `"${dataUri}"`);
}

// Escape for template literal
const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/embed-dashboard.ts — do not edit\nexport const DASHBOARD_HTML = \`${escaped}\`;\n`,
  "utf-8"
);

console.log(`✓ Embedded dashboard HTML + ${iconFiles.length} icons into ${outPath}`);
