#!/usr/bin/env bun
// Generates src/dashboard/embedded-icons.ts with icon files as base64 buffers.
// The dashboard server serves them via /icons/ route with correct MIME types.

import { join } from "path";
import { writeFileSync } from "fs";

const root = join(import.meta.dir, "..");
const iconsDir = join(root, "src", "dashboard", "public", "icons");
const outPath = join(root, "src", "dashboard", "embedded-icons.ts");

const MIME: Record<string, string> = {
  ico: "image/x-icon",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  svg: "image/svg+xml",
};

const iconFiles = ["claude-code.ico", "gemini-cli.ico", "opencode.png", "copilot.jpg", "codex.png"];

const entries: string[] = [];

for (const file of iconFiles) {
  const ext = file.split(".").pop()!;
  const mime = MIME[ext] ?? "application/octet-stream";
  const bytes = await Bun.file(join(iconsDir, file)).arrayBuffer();
  const b64 = Buffer.from(bytes).toString("base64");
  entries.push(`  "${file}": { mime: "${mime}", data: "${b64}" }`);
}

const logoSvg = await Bun.file(join(root, "src", "dashboard", "public", "logo.svg")).text();
const escapedLogo = logoSvg.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/embed-icons.ts — do not edit\nexport const EMBEDDED_ICONS: Record<string, { mime: string; data: string }> = {\n${entries.join(",\n")}\n};\nexport const LOGO_SVG = \`${escapedLogo}\`;\n`,
  "utf-8"
);

console.log(`✓ Embedded ${iconFiles.length} icons + logo into ${outPath}`);
