#!/usr/bin/env bun
// Generates src/dashboard/embedded-html.ts with the dashboard HTML inlined.
// Icons are inlined as base64 data URIs so the binary is fully self-contained.

import { join } from "path";
import { writeFileSync } from "fs";

const root = join(import.meta.dir, "..");
const htmlPath = join(root, "src", "dashboard", "public", "index.html");
const outPath = join(root, "src", "dashboard", "embedded-html.ts");

let html = await Bun.file(htmlPath).text();

// Escape for template literal
const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/embed-dashboard.ts — do not edit\nexport const DASHBOARD_HTML = \`${escaped}\`;\n`,
  "utf-8"
);

console.log(`✓ Embedded dashboard HTML into ${outPath}`);
